version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: SendToKindle
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongodb_data:/data/db
volumes:
  mongodb_data: