version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: SendToKindle
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: